# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen4.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen4(object):
    def setupUi(self, Screen4_Window):
        Screen4_Window.setObjectName("Screen4_Window")
        Screen4_Window.resize(705, 491)
        self.centralwidget = QtWidgets.QWidget(Screen4_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.Screen4Image = QtWidgets.QLabel(self.centralwidget)
        self.Screen4Image.setGeometry(QtCore.QRect(0, 70, 701, 391))
        self.Screen4Image.setAutoFillBackground(True)
        self.Screen4Image.setText("")
        self.Screen4Image.setPixmap(QtGui.QPixmap("Images/metro9.jpg"))
        self.Screen4Image.setScaledContents(True)
        self.Screen4Image.setIndent(34)
        self.Screen4Image.setObjectName("Screen4Image")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 691, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setIndent(60)
        self.label.setObjectName("label")
        self.AgeGenderCombo = QtWidgets.QComboBox(self.centralwidget)
        self.AgeGenderCombo.setGeometry(QtCore.QRect(20, 140, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AgeGenderCombo.setFont(font)
        self.AgeGenderCombo.setMaxVisibleItems(12)
        self.AgeGenderCombo.setObjectName("AgeGenderCombo")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.AgeGenderCombo.addItem("")
        self.Screen4_SubmitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.Screen4_SubmitBtn.setGeometry(QtCore.QRect(100, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Screen4_SubmitBtn.setFont(font)
        self.Screen4_SubmitBtn.setMouseTracking(True)
        self.Screen4_SubmitBtn.setAutoFillBackground(True)
        self.Screen4_SubmitBtn.setAutoDefault(False)
        self.Screen4_SubmitBtn.setDefault(False)
        self.Screen4_SubmitBtn.setFlat(False)
        self.Screen4_SubmitBtn.setObjectName("Screen4_SubmitBtn")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(60, 330, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BackButton.setFont(font)
        self.BackButton.setMouseTracking(True)
        self.BackButton.setAutoFillBackground(True)
        self.BackButton.setAutoDefault(False)
        self.BackButton.setDefault(False)
        self.BackButton.setFlat(False)
        self.BackButton.setObjectName("BackButton")
        #Screen4_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Screen4_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        '''
        self.menubar.setObjectName("menubar")
        Screen4_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Screen4_Window)
        self.statusbar.setObjectName("statusbar")
        Screen4_Window.setStatusBar(self.statusbar)
        '''
        self.retranslateUi(Screen4_Window)
        QtCore.QMetaObject.connectSlotsByName(Screen4_Window)

    def retranslateUi(self, Screen4_Window):
        _translate = QtCore.QCoreApplication.translate
        Screen4_Window.setWindowTitle(_translate("Screen4_Window", "Screen4_Window"))
        self.label.setText(_translate("Screen4_Window", "AGE AND GENDER DISTRIBUTION"))
        self.AgeGenderCombo.setItemText(0, _translate("Screen4_Window", "Sunday"))
        self.AgeGenderCombo.setItemText(1, _translate("Screen4_Window", "Monday"))
        self.AgeGenderCombo.setItemText(2, _translate("Screen4_Window", "Tuesday"))
        self.AgeGenderCombo.setItemText(3, _translate("Screen4_Window", "Wednesday"))
        self.AgeGenderCombo.setItemText(4, _translate("Screen4_Window", "Thursday"))
        self.AgeGenderCombo.setItemText(5, _translate("Screen4_Window", "Friday"))
        self.AgeGenderCombo.setItemText(6, _translate("Screen4_Window", "Saturday"))
        self.AgeGenderCombo.setItemText(7, _translate("Screen4_Window", "Weekends"))
        self.AgeGenderCombo.setItemText(8, _translate("Screen4_Window", "Weekdays"))
        self.AgeGenderCombo.setItemText(9, _translate("Screen4_Window", "Holidays"))
        self.Screen4_SubmitBtn.setText(_translate("Screen4_Window", "SUBMIT"))
        self.BackButton.setText(_translate("Screen4_Window", "BACK"))
